### PR TITLE
command to print what's inside the state cache

### PR DESCRIPTION
**Pull request by Dieterbe**
Is this useful? feel free to close. I just added this command to help me understand what's going on.

### CODE REVIEW

**Comment by naggie** [comment]
Just printing a `CmdLine` object merged with the context would do it. I'd rather not add commands that aren't useful to the normal workflow. Exceptionally, some commands are hidden (such as `_completions`) and they're prefixed by an underscore.

Thanks for the effort nonetheless.

**Comment by Dieterbe** [comment]
> Just printing a CmdLine object merged with the context would do it.

Note that CmdLine.String() does not print the .Cmd property, nor the .IgnoreContext and .Note properties. 
I'm not sure why this is but that's the reason my code does slightly more than showing CmdLine.String(), it also shows those properties.

**Comment by naggie** [comment]
I see, the reason is it's used to show the current context where the command is irrelevant, and the ignore context boolean would invalidate it anyway

**Comment by naggie** [comment]
PS: It's cool you work at Grafana!

**Pull request closed without merging**
