### PR TITLE
move command to cmd/dstask

### PR DESCRIPTION
**Pull request by Dieterbe**
this is the de facto standard. e.g. see
https://github.com/golang-standards/project-layout#go-directories

Previously, running 'go install github.com/naggie/dstask/cmd' or
'cd $GOPATH/src/github.com/naggie/dstask/cmd && go install .'
would result in a binary named 'cmd'

The best practice is to put binaries in a directory named after the
binary, that way you always get the right name

### CODE REVIEW

**Comment by naggie** [comment]
Oh, that makes sense and I've been meaning do do that. Thanks. Please also update `smoketest.sh` and `do-release.sh`

**Comment by Dieterbe** [comment]
interestingly running `go build` without an `-o` flag now generates a binary named `main`, whereas it would previously correctly build a binary named `dstask`. kindof ironic compared to the `go install` story... it seems to behave the opposite.

anyway, this is still more conventional this way.

**Comment by naggie** [comment]
That's why I stopped work on trying to fix it. I think I found it also depends on the go version. I'll check the Nix/Arch/FreeBSD packages before merging as it might affect them too (though I don't maintain them)

**Comment by Dieterbe** [comment]
okay.
i just noticed something else that's interesting. in the Makefile we call `mkdir -p dstask` perhaps that should be `dist` instead.
but then again `go build -mod=vendor -o dist/dstask cmd/dstask/main.go` seems to auto-create dist if it didn't exist yet, so we can probably just remove the mkdir line.

**Comment by naggie** [comment]
Hm, yes it should. Well spotted!

**Comment by naggie** [comment]
Actually thinking about it, I can't think of a reason it shouldn't just be `/dstask/main.go` -- there's no need for `cmd`

**Comment by Dieterbe** [comment]
`cmd/<binaryname>` is a well established pattern in go project layouts. I would advise to stick to it.  makes it clear where are the entrypoints to the commands live.

**Pull request merged**
